Repository Phixyn/no-bs-looper, pull requests merged in 2020-10, with the labels that each got.

#73 Text selection colour
  static/css/app.css
Labels: ui

#76 Feat: Allow using YouTube links in addition to video IDs
  docs/devlog.md
  static/index.html
  static/js/app.js
Labels: frontend client, new feature

#82 Feat: Form input validation
  docs/devlog.md
  static/css/app.css
  static/index.html
  static/js/app.js
Labels: frontend client, improvement, ui

#83 Refactor: Check server messages in client's message handler
  static/js/app.js
  ws_server.py
Labels: backend, frontend client, refactor

#85 Feat: Share link modal and copy
  docs/devlog.md
  static/css/app.css
  static/index.html
  static/js/app.js
Labels: foundation, frontend client, new feature, ui

#86 Looper: Update meta tags
  static/index.html
Labels: refactor

#88 Feat: Add a shadow around the player
  docs/devlog.md
  static/css/app.css
  static/index.html
Labels: improvement, ui

#90 Feat: Turn off the lights
  static/css/app.css
  static/index.html
  static/js/app.js
Labels: new feature, ui

#93 Release/1.1.0
  CHANGELOG.md
  README.md
  docs/screenshots/desktop_demo_full2.png
  docs/screenshots/desktop_demo_yt_controls.png
Labels: documentation
